### ISSUE TITLE
More Options

### ISSUE THREAD

**Issue by lfiocco** [underbluewaters/homebridge-sainsmart-16-usb#2]
Any way to allow relays to switch of after a short time. example 1000ms. or add different types like sprinklers?

**Comment by underbluewaters** [comment]
I don't support the HomeKit sprinkler type because it has a bunch of required metadata around duration and other properties that this library doesn't handle. I'd like this to remain more general-purpose to handle the basic needs of turning on and off relays.
It would be nice to have something that could be a more fully-featured irrigation controller but I think that would be best handled by a new plugin.
